### ISSUE TITLE
pin_stm32F4xx.h, enum PinAltFunction

### ISSUE THREAD

**Issue by esaulenka** [antongus/stm32tpl#2]
В enum'е PinAltFunction названия для USB недостаточно понятные.

Убил вчера весь день, пока не выяснил, что
```
	ALT_FUNC_OTG_FS    = 0x0A,          // OTG_FS с встроенным трансивером
	ALT_FUNC_OTG_HS    = 0x0A,          // OTG_HS с внешним трансивером
	ALT_FUNC_OTG_HS_FS = 0x0C,          // OTG HS с встроенным трансивером
```
Прошу переименовать второй, скажем, в
```
	ALT_FUNC_OTG_HS_ULPI    = 0x0A,          // OTG_HS с внешним трансивером
```

**Comment by antongus** [comment]
Я не стал переименовывать, просто добавил эту строчку. Ну, чтобы не поломались проекты, которые используют старый вариант. Заодно комменты немного поконкретнее сделал.

Коммит fe8d63e8cfd595cee3de3f14b6cac6cfe7014cef.
